"""empty message

Revision ID: 445a193abd40
Revises: None
Create Date: 2016-10-20 08:22:58.796151

"""

# revision identifiers, used by Alembic.
revision = '445a193abd40'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good', sa.String(length=64), nullable=True),
    sa.Column('bad', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('_password', sa.String(length=64), nullable=True),
    sa.Column('reg_time', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hbentries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hb_id', sa.Integer(), nullable=True),
    sa.Column('good', sa.String(length=64), nullable=True),
    sa.Column('bad', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['hb_id'], ['hobbies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hbentries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('hobbies')
    op.drop_table('entries')
    ### end Alembic commands ###
